version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./index.json:/app/index.json
      # Map the Windows network share into the container
      - /mnt/photos:/data/share:ro
    restart: unless-stopped
